tool = "xschem-lvs"
schematic = "Mixer5GHz.sch"
netlist = "Mixer5GHz.spice"

[[files]]
checkout = "to_apr2025"
path = "Mixer5GHz/design_data/xschem/Mixer5GHz.sch"
target = "Mixer5GHz.sch"
sha256 = "9d6ba0d47a052db524d36e6bfc1221f327cd16ba1ee2fe20d64b19c4daa6cd08"

[[files]]
checkout = "pdk"
path = "ihp-sg13g2/libs.tech/xschem/sg13g2_pr/sg13_lv_nmos.sym"
target = "sg13g2_pr/sg13_lv_nmos.sym"
sha256 = "4c65869259c7aea7ff30d8612c5017419423d55e27dbb0aea28323e7da49ba7d"

[[files]]
checkout = "pdk"
path = "ihp-sg13g2/libs.tech/xschem/sg13g2_pr/rppd.sym"
target = "sg13g2_pr/rppd.sym"
sha256 = "8f2cb46afa2a1be1e445b05ab22cb5f42473a43a49d3d1d08f181f683daf640b"

[[files]]
checkout = "pdk"
path = "ihp-sg13g2/libs.tech/xschem/sg13g2_pr/cap_cmim.sym"
target = "sg13g2_pr/cap_cmim.sym"
sha256 = "b11c811ee178d260c4b7afcaa8c123f8a6c8c108dde1a119c91aa4386d24e20b"
